---
- name: Vérifier que la distribution est bien Debian 12
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version == "12"
    fail_msg: "Please run this playbook on Debian 12.x only."
